    <nav>
        <ul id="navbar">
            <li><a href="index.php">Home </a></li>
            <li><a href="jobs.php">Job </a></li>
            <li><a href="apply.php" title="Get great opportunity"> Apply </a></li>
            <li><a href="about.php">About </a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="enhancements2.php">Enhancements2</a></li>
            <li><a href="mailto:103503476@student.swin.edu.au">Contact</a></li>
            <li><a href="login.php">Login</a></li>
            <li><a href="phpenhancements.php">phpenhancements</a></li>

        </ul>
    </nav>